/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    IconEvaExternalLinkFill: typeof import('~icons/eva/external-link-fill')['default']
    IconFa6SolidCopy: typeof import('~icons/fa6-solid/copy')['default']
    IconFa6SolidLocationCrosshairs: typeof import('~icons/fa6-solid/location-crosshairs')['default']
    IconMingcuteMountain2Fill: typeof import('~icons/mingcute/mountain2-fill')['default']
    QIconify: typeof import('./src/components/quasar/QIconify.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    WdFeedbackButton: typeof import('./src/components/feedback/WdFeedbackButton.vue')['default']
    WdFeedbackForm: typeof import('./src/components/feedback/WdFeedbackForm.vue')['default']
    WdHutHeader: typeof import('./src/components/huts/WdHutHeader.vue')['default']
    WdHutOpenMonthly: typeof import('./src/components/huts/monthly/WdHutOpenMonthly.vue')['default']
    WdHutToolbar: typeof import('./src/components/huts/WdHutToolbar.vue')['default']
    WdHutType: typeof import('./src/components/huts/WdHutType.vue')['default']
    WdHutTypeChip: typeof import('./src/components/huts/WdHutTypeChip.vue')['default']
    WdHutTypeNameChip: typeof import('./src/components/huts/WdHutTypeNameChip.vue')['default']
    WdHutView: typeof import('./src/components/huts/WdHutView.vue')['default']
    WdMapContent: typeof import('./src/components/map/WdMapContent.vue')['default']
    WdMapMenu: typeof import('./src/components/map/WdMapMenu.vue')['default']
    WdMapStyleSwitcher: typeof import('./src/components/map/WdMapStyleSwitcher.vue')['default']
    WdMapStyleSwitchItem: typeof import('./src/components/map/WdMapStyleSwitchItem.vue')['default']
    WdMapView: typeof import('./src/components/map/WdMapView.vue')['default']
    WdMenuButton: typeof import('./src/components/toolbar/WdMenuButton.vue')['default']
    WdMonthly: typeof import('./src/components/huts/monthly/WdMonthly.vue')['default']
    WdSourceButtons: typeof import('./src/components/huts/WdSourceButtons.vue')['default']
    WdToolbarButton: typeof import('./src/components/toolbar/WdToolbarButton.vue')['default']
    WodoreLogo: typeof import('./src/components/wodore/WodoreLogo.vue')['default']
  }
}
