// GENERATED by scripts/gen-api.mjs (yarn gen:api / gen:api-local) — do not edit.
// Source schema: http://127.0.0.1:8020/v1/openapi.json
// DELIBERATE HAND PIN: held at the backend's current UNRELEASED version so the
// app rides the latest contract on staging (e.g. the gallery static-map
// fallback). `yarn gen:api` resets this to the schema's info.version — restore
// 'unreleased' until the next coordinated backend api-release re-pins us.
export const PINNED_API_VERSION = 'unreleased';
