/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  '/v1/huts/bookings': {
    /**
     * Get hut bookings (deprecated)
     * @deprecated
     * @description **DEPRECATED**: Use `/huts/availability.geojson` instead. This endpoint will be removed in a future version.
     */
    get: operations['get_hut_bookings'];
  };
  '/v1/huts/bookings.geojson': {
    /**
     * Get hut bookings as GeoJSON (deprecated)
     * @deprecated
     * @description **DEPRECATED**: Use `/huts/availability.geojson` instead. This endpoint will be removed in a future version.
     */
    get: operations['get_hut_bookings_geojson'];
  };
  '/v1/huts/types/list': {
    /** Get Hut Types */
    get: operations['get_hut_types'];
  };
  '/v1/huts/types/records': {
    /** Get Hut Type Records */
    get: operations['get_hut_type_records'];
  };
  '/v1/huts/availability/{date}.geojson': {
    /**
     * Get Hut Availability Geojson
     * @description Get availability data as GeoJSON FeatureCollection for map visualization.
     */
    get: operations['get_hut_availability_geojson'];
  };
  '/v1/huts/{slug}/availability/{date}': {
    /**
     * Get Hut Availability Current
     * @description Get current availability data for a specific hut with detailed metadata and booking links.
     */
    get: operations['get_hut_availability_current'];
  };
  '/v1/huts/{slug}/availability/{date}/trend': {
    /**
     * Get Hut Availability Trend
     * @description Get historical availability trend data showing how availability changed over time for a specific date.
     */
    get: operations['get_hut_availability_trend'];
  };
  '/v1/huts/huts': {
    /**
     * Get Huts
     * @description Get a list with huts.
     */
    get: operations['get_huts'];
  };
  '/v1/huts/huts.geojson': {
    /** Get Huts Geojson */
    get: operations['get_huts_geojson'];
  };
  '/v1/huts/{slug}': {
    /**
     * Get Hut
     * @description Get a hut by its slug.
     */
    get: operations['get_hut'];
  };
  '/v1/organizations/': {
    /**
     * Get Organizations
     * @description Get a list of all organizations used for the huts.
     */
    get: operations['get_organizations'];
  };
  '/v1/organizations/{slug}': {
    /** Get Organization */
    get: operations['get_organization'];
  };
  '/v1/feedback/': {
    /** Create Feedback */
    post: operations['server_apps_feedbacks_api_create_feedback'];
  };
}

export type webhooks = Record<string, never>;

export interface components {
  schemas: {
    /** HutBookingsQuery */
    HutBookingsQuery: {
      /**
       * Slugs
       * @description Comma separated list with slugs to use, per default all.
       */
      slugs?: string | null;
      /**
       * Days
       * @description Show bookings for this many days.
       * @default 1
       */
      days?: number;
      /**
       * Date
       * @description Date to start with bookings (yyyy-mm-dd, 'now' or 'weekend').
       * @default now
       */
      date?: string | ('now' | 'weekend');
      /**
       * Request interval
       * @description Time in seconds to wait between requests to the booking service for each hut. If not set uses recommanded default value.
       */
      request_interval?: number | null;
    };
    /** HutBookingSchema */
    HutBookingSchema: {
      /** Link */
      link: string;
      /**
       * Date
       * Format: date
       */
      date: string;
      reservation_status: components['schemas']['ReservationStatusEnum'];
      /** Free */
      free: number;
      /** Total */
      total: number;
      /** Occupancy Percent */
      occupancy_percent: number;
      /** Occupancy Steps */
      occupancy_steps: number;
      occupancy_status: components['schemas']['OccupancyStatusEnum'];
      /**
       * Hut Type
       * @default unknown
       */
      hut_type?: string;
    };
    /** HutBookingsSchema */
    HutBookingsSchema: {
      /** Slug */
      slug: string;
      /** Hut Id */
      hut_id: number;
      /**
       * Source Id
       * @description External source organization's ID for this hut
       */
      source_id: string;
      /**
       * Source
       * @description Source slug, e.g. hrs
       */
      source: string;
      /** Days */
      days: number;
      /** Link */
      link: string;
      /**
       * Start Date
       * Format: date
       */
      start_date: string;
      /** Bookings */
      bookings: components['schemas']['HutBookingSchema'][];
      location: components['schemas']['LocationSchema'];
    };
    /**
     * LocationSchema
     * @description Location with longitude, latitude and optional elevation in WSG84.
     *
     * Attributes:
     *     lon: Longitude (x).
     *     lat: Latitude (y).
     *     ele: Elevation in meter.
     */
    LocationSchema: {
      /** Latitude (y) in WGS84 */
      lat: number;
      /** Longitude (x) in WGS84 */
      lon: number;
    };
    /**
     * OccupancyStatusEnum
     * @description Enum with with occuptation status.
     * @enum {string}
     */
    OccupancyStatusEnum:
      | 'unknown'
      | 'empty'
      | 'low'
      | 'medium'
      | 'high'
      | 'full';
    /**
     * ReservationStatusEnum
     * @description Enum with reservation status.
     * @enum {string}
     */
    ReservationStatusEnum:
      | 'unknown'
      | 'possible'
      | 'not_possible'
      | 'not_online';
    /** Feature[Point, HutBookingsProps] */
    Feature_Point_HutBookingsProps_: {
      /** Bbox */
      bbox?:
        | [number, number, number, number]
        | [number, number, number, number, number, number]
        | null;
      /**
       * Type
       * @constant
       */
      type: 'Feature';
      geometry: components['schemas']['Point'] | null;
      properties: components['schemas']['HutBookingsProps'] | null;
      /** Id */
      id?: number | string | null;
    };
    /** HutBookingsFeatureCollection */
    HutBookingsFeatureCollection: {
      /** Bbox */
      bbox?:
        | [number, number, number, number]
        | [number, number, number, number, number, number]
        | null;
      /**
       * Type
       * @constant
       */
      type: 'FeatureCollection';
      /** Features */
      features: components['schemas']['Feature_Point_HutBookingsProps_'][];
    };
    /** HutBookingsProps */
    HutBookingsProps: {
      /** Slug */
      slug: string;
      /** Hut Id */
      hut_id: number;
      /**
       * Source Id
       * @description External source organization's ID for this hut
       */
      source_id: string;
      /**
       * Source
       * @description Source slug, e.g. hrs
       */
      source: string;
      /** Days */
      days: number;
      /** Link */
      link: string;
      /**
       * Start Date
       * Format: date
       */
      start_date: string;
      /** Bookings */
      bookings: components['schemas']['HutBookingSchema'][];
    };
    /**
     * Point
     * @description Point Model
     */
    Point: {
      /** Bbox */
      bbox?:
        | [number, number, number, number]
        | [number, number, number, number, number, number]
        | null;
      /**
       * Type
       * @constant
       */
      type: 'Point';
      /** Coordinates */
      coordinates:
        | components['schemas']['Position2D']
        | components['schemas']['Position3D'];
    };
    Position2D: [number, number];
    Position3D: [number, number, number];
    /** FieldsParam[HutTypeDetailSchema] */
    FieldsParam_HutTypeDetailSchema_: {
      /**
       * Include
       * @description Comma separated list with field names, use `__all__` in order to include every field.
       */
      include?: unknown;
      /**
       * Exclude
       * @description Comma separated list with field names, if set it uses all fields except the excluded ones.
       */
      exclude?: unknown;
    };
    /** HutTypeDetailSchema */
    HutTypeDetailSchema: {
      /** Slug */
      slug: string;
      /** Name */
      name: string;
      /**
       * Description
       * @default
       */
      description?: string;
      /**
       * Symbol
       * @description Normal icon
       * @default huts/types/symbols/detailed/unknown.png
       */
      symbol?: string | null;
      /**
       * Level
       * @description Comfort level, higher is more comfort
       * @default 0
       */
      level?: number | null;
      /**
       * Symbol Simple
       * @description Simple icon
       * @default huts/types/symbols/simple/unknown.png
       */
      symbol_simple?: string | null;
      /**
       * Icon
       * @description Black icon
       * @default huts/types/icons/unknown.png
       */
      icon?: string | null;
    };
    /**
     * DatePathParam
     * @description Path parameter for date.
     */
    DatePathParam: {
      /**
       * Date
       * @description Start date. Accepts ISO dates (2026-01-15, 26-01-15), European format (15.01.2026), or keywords: 'now', 'today', 'weekend'.
       */
      date: string;
    };
    /**
     * AvailabilityGeoJSONQuery
     * @description Query parameters for GeoJSON availability endpoint.
     */
    AvailabilityGeoJSONQuery: {
      /**
       * Hut Slugs
       * @description Comma-separated list of hut slugs to filter (e.g., 'aarbiwak,almageller'). If not set, returns all huts.
       */
      slugs?: string | null;
      /**
       * Days
       * @description Number of days to fetch from start date.
       * @default 1
       */
      days?: number;
      /**
       * Offset
       * @description Pagination offset for results.
       * @default 0
       */
      offset?: number;
      /**
       * Limit
       * @description Maximum number of huts to return. If not set, returns all matching huts.
       */
      limit?: number | null;
    };
    /**
     * AvailabilityDaySchema
     * @description Single day's availability data for a hut.
     */
    AvailabilityDaySchema: {
      /**
       * Date
       * Format: date
       * @description Availability date
       */
      date: string;
      /** @description Reservation status (unknown, possible, not_possible, not_online) */
      reservation_status: components['schemas']['ReservationStatusEnum'];
      /**
       * Free
       * @description Number of free places
       */
      free: number;
      /**
       * Total
       * @description Total number of places
       */
      total: number;
      /**
       * Occupancy Percent
       * @description Occupancy percentage (0-100)
       */
      occupancy_percent: number;
      /**
       * Occupancy Steps
       * @description Occupancy in discrete steps (0-100, increments of 10)
       */
      occupancy_steps: number;
      /** @description Occupancy status (empty, low, medium, high, full, unknown) */
      occupancy_status: components['schemas']['OccupancyStatusEnum'];
      /**
       * Hut Type
       * @description Hut type on this date (e.g., 'hut', 'bivouac')
       * @default unknown
       */
      hut_type?: string;
    };
    /** Feature[Point, HutAvailabilityPropertiesSchema] */
    Feature_Point_HutAvailabilityPropertiesSchema_: {
      /** Bbox */
      bbox?:
        | [number, number, number, number]
        | [number, number, number, number, number, number]
        | null;
      /**
       * Type
       * @constant
       */
      type: 'Feature';
      geometry: components['schemas']['Point'] | null;
      properties:
        | components['schemas']['HutAvailabilityPropertiesSchema']
        | null;
      /** Id */
      id?: number | string | null;
    };
    /**
     * HutAvailabilityFeatureCollection
     * @description GeoJSON FeatureCollection of hut availability data.
     */
    HutAvailabilityFeatureCollection: {
      /** Bbox */
      bbox?:
        | [number, number, number, number]
        | [number, number, number, number, number, number]
        | null;
      /**
       * Type
       * @constant
       */
      type: 'FeatureCollection';
      /** Features */
      features: components['schemas']['Feature_Point_HutAvailabilityPropertiesSchema_'][];
    };
    /**
     * HutAvailabilityPropertiesSchema
     * @description Properties for a hut availability GeoJSON feature.
     */
    HutAvailabilityPropertiesSchema: {
      /**
       * Slug
       * @description Hut slug identifier
       */
      slug: string;
      /**
       * Id
       * @description Hut database ID
       */
      id: number;
      /**
       * Source Id
       * @description External source organization's ID for this hut
       */
      source_id: string;
      /**
       * Source
       * @description Source organization slug (e.g., 'hrs', 'sac')
       */
      source: string;
      /**
       * Source Link
       * @description External link to the hut page on the source website
       */
      source_link: string;
      /**
       * Days
       * @description Number of days of availability data
       */
      days: number;
      /**
       * Start Date
       * Format: date
       * @description Start date of availability period
       */
      start_date: string;
      /**
       * Data
       * @description List of availability data for each day
       */
      data: components['schemas']['AvailabilityDaySchema'][];
    };
    /**
     * CurrentAvailabilityQuery
     * @description Query parameters for current availability endpoint.
     */
    CurrentAvailabilityQuery: {
      /**
       * Days
       * @description Number of days to fetch from start date.
       * @default 1
       */
      days?: number;
    };
    /**
     * CurrentAvailabilityDaySchema
     * @description Single day's current availability data with metadata.
     */
    CurrentAvailabilityDaySchema: {
      /**
       * Date
       * Format: date
       * @description Availability date
       */
      date: string;
      /** @description Reservation status (unknown, possible, not_possible, not_online) */
      reservation_status: components['schemas']['ReservationStatusEnum'];
      /**
       * Free
       * @description Number of free places
       */
      free: number;
      /**
       * Total
       * @description Total number of places
       */
      total: number;
      /**
       * Occupancy Percent
       * @description Occupancy percentage (0-100)
       */
      occupancy_percent: number;
      /**
       * Occupancy Steps
       * @description Occupancy in discrete steps (0-100, increments of 10)
       */
      occupancy_steps: number;
      /** @description Occupancy status (empty, low, medium, high, full, unknown) */
      occupancy_status: components['schemas']['OccupancyStatusEnum'];
      /**
       * Hut Type
       * @description Hut type on this date (e.g., 'hut', 'bivouac')
       * @default unknown
       */
      hut_type?: string;
      /**
       * Link
       * @description Booking link for this date
       */
      link: string;
      /**
       * First Checked
       * Format: date-time
       * @description When this availability was first recorded
       */
      first_checked: string;
      /**
       * Last Checked
       * Format: date-time
       * @description When this availability was last checked
       */
      last_checked: string;
    };
    /**
     * CurrentAvailabilitySchema
     * @description Current availability data for a specific hut.
     */
    CurrentAvailabilitySchema: {
      /**
       * Slug
       * @description Hut slug identifier
       */
      slug: string;
      /**
       * Id
       * @description Hut database ID
       */
      id: number;
      /**
       * Source Id
       * @description External source organization's ID for this hut
       */
      source_id: string;
      /**
       * Source Link
       * @description External source organization's link for this hut
       */
      source_link: string;
      /**
       * Source
       * @description Source organization slug (e.g., 'hrs', 'sac')
       */
      source: string;
      /**
       * Days
       * @description Number of days of availability data
       */
      days: number;
      /**
       * Start Date
       * Format: date
       * @description Start date of availability period
       */
      start_date: string;
      /**
       * Data
       * @description List of current availability data for each day
       */
      data: components['schemas']['CurrentAvailabilityDaySchema'][];
    };
    /**
     * DatePathParamTrend
     * @description Path parameter for trend endpoint.
     */
    DatePathParamTrend: {
      /**
       * Date
       * @description Target date to analyze. Accepts ISO dates (2026-01-15, 26-01-15), European format (15.01.2026), or keywords: 'now', 'today', 'weekend'.
       */
      date: string;
    };
    /**
     * AvailabilityTrendQuery
     * @description Query parameters for availability trend endpoint.
     */
    AvailabilityTrendQuery: {
      /**
       * Limit
       * @description How many days back to show history from the target date.
       * @default 7
       */
      limit?: number;
    };
    /**
     * AvailabilityTrendDaySchema
     * @description Single historical availability data point.
     */
    AvailabilityTrendDaySchema: {
      /**
       * Date
       * Format: date
       * @description Availability date this data applies to
       */
      date: string;
      /**
       * Free
       * @description Number of free places
       */
      free: number;
      /**
       * Total
       * @description Total number of places
       */
      total: number;
      /**
       * Occupancy Percent
       * @description Occupancy percentage (0-100)
       */
      occupancy_percent: number;
      /** @description Occupancy status (empty, low, medium, high, full, unknown) */
      occupancy_status: components['schemas']['OccupancyStatusEnum'];
      /** @description Reservation status (unknown, possible, not_possible, not_online) */
      reservation_status: components['schemas']['ReservationStatusEnum'];
      /**
       * Hut Type
       * @description Hut type on this date (e.g., 'hut', 'bivouac')
       * @default unknown
       */
      hut_type?: string;
      /**
       * First Checked
       * Format: date-time
       * @description When this state was first observed
       */
      first_checked: string;
      /**
       * Last Checked
       * Format: date-time
       * @description When this state was last confirmed
       */
      last_checked: string;
    };
    /**
     * AvailabilityTrendSchema
     * @description Historical availability trend data for a specific hut and date.
     */
    AvailabilityTrendSchema: {
      /**
       * Slug
       * @description Hut slug identifier
       */
      slug: string;
      /**
       * Id
       * @description Hut database ID
       */
      id: number;
      /**
       * Target Date
       * Format: date
       * @description The date for which trend data is shown
       */
      target_date: string;
      /**
       * Period Start
       * Format: date
       * @description Start of the trend period (target_date - limit days)
       */
      period_start: string;
      /**
       * Period End
       * Format: date
       * @description End of the trend period (target_date)
       */
      period_end: string;
      /**
       * Data
       * @description Historical availability changes, ordered by first_checked (newest first)
       */
      data: components['schemas']['AvailabilityTrendDaySchema'][];
    };
    /**
     * TristateEnum
     * @description Tristate enum with `true`, `false` and `unset`.
     * @enum {string}
     */
    TristateEnum: 'true' | 'false' | 'unset';
    /**
     * AnswerEnum
     * @description Anser enum.
     *
     * 'yesish' and 'noish' means it is likely to be 'yes' or 'no'.
     * 'maybe' means is is either 'yes' or 'no'.
     * @enum {string}
     */
    AnswerEnum: 'yes' | 'yesish' | 'maybe' | 'noish' | 'no' | 'unknown';
    CountryTuple: [string, string];
    /** HutSchemaDetails */
    HutSchemaDetails: {
      /** Slug */
      slug: string;
      /** Name */
      name: string | null;
      /** Description */
      description: string | null;
      /** Description Attribution */
      description_attribution: string;
      owner: components['schemas']['OwnerSchema'] | null;
      /** Review Status */
      review_status?: string | null;
      /** Is Public */
      is_public?: boolean | null;
      /** Is Active */
      is_active?: boolean | null;
      /** Is Modified */
      is_modified?: boolean | null;
      type_open?: components['schemas']['HutTypeSchema'] | null;
      type_closed?: components['schemas']['HutTypeSchema'] | null;
      /** Elevation */
      elevation?: number | null;
      location?: components['schemas']['LocationSchema'] | null;
      /** Url */
      url?: string | null;
      country?: components['schemas']['CountryTuple'] | null;
      /** Capacity Open */
      capacity_open?: number | null;
      /** Capacity Closed */
      capacity_closed?: number | null;
      /** Sources */
      sources: components['schemas']['OrganizationBaseSchema'][] | null;
      /**
       * Photos
       * @default
       */
      photos?: string;
      /**
       * Photos Attribution
       * @default
       */
      photos_attribution?: string;
      /** Images */
      images: components['schemas']['ImageInfoSchema'][] | null;
      open_monthly?: components['schemas']['OpenMonthlySchema'] | null;
      /** Edit Link */
      edit_link?: string | null;
      /** Translations */
      translations?: unknown;
    };
    /** HutTypeSchema */
    HutTypeSchema: {
      /** Level */
      level?: number | null;
      /** Slug */
      slug: string;
      /** Name */
      name: string | null;
      /** Symbol */
      symbol: string | null;
      /** Symbol Simple */
      symbol_simple: string | null;
      /** Icon */
      icon: string | null;
    };
    /** ImageInfoSchema */
    ImageInfoSchema: {
      /** Image */
      image: string;
      image_meta: components['schemas']['ImageMetaSchema'];
      license: components['schemas']['LicenseInfoSchema'];
      /** Author */
      author?: string | null;
      /** Caption */
      caption?: string | null;
      /** Author Url */
      author_url?: string | null;
      /** Source Url */
      source_url?: string | null;
      organization?: components['schemas']['OrganizationImageSchema'] | null;
      /** Attribution */
      attribution?: string | null;
      /**
       * Urls
       * @description Return the image URL with the transformations applied.
       */
      urls: {
        [key: string]: string;
      };
    };
    /** ImageMetaAreaSchema */
    ImageMetaAreaSchema: {
      /** X1 */
      x1: number;
      /** X2 */
      x2: number;
      /** Y1 */
      y1: number;
      /** Y2 */
      y2: number;
    };
    /** ImageMetaSchema */
    ImageMetaSchema: {
      crop?: components['schemas']['ImageMetaAreaSchema'] | null;
      focal?: components['schemas']['ImageMetaAreaSchema'] | null;
      /** Width */
      width?: number | null;
      /** Height */
      height?: number | null;
    };
    /**
     * LicenseInfoSchema
     * @description Important information, for example for an image
     */
    LicenseInfoSchema: {
      /** Slug */
      slug: string;
      /** Name */
      name: string | null;
      /** Fullname */
      fullname: string | null;
      /** Description */
      description?: string | null;
      /** Link */
      link?: string | null;
    };
    /**
     * OpenMonthlySchema
     * @description Shows for every month if it is usally, open, partially open or closed.
     * Can be accessed as index, but it starts with 1 (month_01)!.
     *
     * Attributes:
     *     url: URL which shows if it is open or not.
     *     month_mm (OpenMonthly): Month (starting with 01).
     */
    OpenMonthlySchema: {
      /**
       * Url
       * @description URL which shows if it is open or not.
       * @default
       */
      url?: string;
      /** @default unknown */
      month_01?: components['schemas']['AnswerEnum'];
      /** @default unknown */
      month_02?: components['schemas']['AnswerEnum'];
      /** @default unknown */
      month_03?: components['schemas']['AnswerEnum'];
      /** @default unknown */
      month_04?: components['schemas']['AnswerEnum'];
      /** @default unknown */
      month_05?: components['schemas']['AnswerEnum'];
      /** @default unknown */
      month_06?: components['schemas']['AnswerEnum'];
      /** @default unknown */
      month_07?: components['schemas']['AnswerEnum'];
      /** @default unknown */
      month_08?: components['schemas']['AnswerEnum'];
      /** @default unknown */
      month_09?: components['schemas']['AnswerEnum'];
      /** @default unknown */
      month_10?: components['schemas']['AnswerEnum'];
      /** @default unknown */
      month_11?: components['schemas']['AnswerEnum'];
      /** @default unknown */
      month_12?: components['schemas']['AnswerEnum'];
      [key: string]: unknown;
    };
    /** OrganizationBaseSchema */
    OrganizationBaseSchema: {
      /** Slug */
      slug: string;
      /** Name */
      name: string;
      /** Fullname */
      fullname: string;
      /** Link */
      link: string;
      /** Logo */
      logo: string;
      /** Public */
      public: boolean;
      /** Source Id */
      source_id: string;
    };
    /** OrganizationImageSchema */
    OrganizationImageSchema: {
      /** Slug */
      slug: string | null;
      /** Name */
      name: string | null;
      /** Fullname */
      fullname: string | null;
      /** Link */
      link: string | null;
      /** Logo */
      logo: string | null;
    };
    /** OwnerSchema */
    OwnerSchema: {
      /** Name */
      name: string | null;
      /** Slug */
      slug: string;
      /**
       * Adresse (URL)
       * @default
       */
      url?: string | null;
    };
    /** BaseModel */
    BaseModel: Record<string, never>;
    /**
     * Feature
     * @description Feature Model
     */
    Feature: {
      /** Bbox */
      bbox?:
        | [number, number, number, number]
        | [number, number, number, number, number, number]
        | null;
      /**
       * Type
       * @constant
       */
      type: 'Feature';
      /** Geometry */
      geometry:
        | (
            | components['schemas']['Point']
            | components['schemas']['MultiPoint']
            | components['schemas']['LineString']
            | components['schemas']['MultiLineString']
            | components['schemas']['Polygon']
            | components['schemas']['MultiPolygon']
            | components['schemas']['GeometryCollection']
          )
        | null;
      /** Properties */
      properties:
        | {
            [key: string]: unknown;
          }
        | components['schemas']['BaseModel']
        | null;
      /** Id */
      id?: number | string | null;
    };
    /**
     * FeatureCollection
     * @description FeatureCollection Model
     */
    FeatureCollection: {
      /** Bbox */
      bbox?:
        | [number, number, number, number]
        | [number, number, number, number, number, number]
        | null;
      /**
       * Type
       * @constant
       */
      type: 'FeatureCollection';
      /** Features */
      features: components['schemas']['Feature'][];
    };
    /**
     * GeometryCollection
     * @description GeometryCollection Model
     */
    GeometryCollection: {
      /** Bbox */
      bbox?:
        | [number, number, number, number]
        | [number, number, number, number, number, number]
        | null;
      /**
       * Type
       * @constant
       */
      type: 'GeometryCollection';
      /** Geometries */
      geometries: (
        | components['schemas']['Point']
        | components['schemas']['MultiPoint']
        | components['schemas']['LineString']
        | components['schemas']['MultiLineString']
        | components['schemas']['Polygon']
        | components['schemas']['MultiPolygon']
        | components['schemas']['GeometryCollection']
      )[];
    };
    /**
     * LineString
     * @description LineString Model
     */
    LineString: {
      /** Bbox */
      bbox?:
        | [number, number, number, number]
        | [number, number, number, number, number, number]
        | null;
      /**
       * Type
       * @constant
       */
      type: 'LineString';
      /** Coordinates */
      coordinates: (
        | components['schemas']['Position2D']
        | components['schemas']['Position3D']
      )[];
    };
    /**
     * MultiLineString
     * @description MultiLineString Model
     */
    MultiLineString: {
      /** Bbox */
      bbox?:
        | [number, number, number, number]
        | [number, number, number, number, number, number]
        | null;
      /**
       * Type
       * @constant
       */
      type: 'MultiLineString';
      /** Coordinates */
      coordinates: (
        | components['schemas']['Position2D']
        | components['schemas']['Position3D']
      )[][];
    };
    /**
     * MultiPoint
     * @description MultiPoint Model
     */
    MultiPoint: {
      /** Bbox */
      bbox?:
        | [number, number, number, number]
        | [number, number, number, number, number, number]
        | null;
      /**
       * Type
       * @constant
       */
      type: 'MultiPoint';
      /** Coordinates */
      coordinates: (
        | components['schemas']['Position2D']
        | components['schemas']['Position3D']
      )[];
    };
    /**
     * MultiPolygon
     * @description MultiPolygon Model
     */
    MultiPolygon: {
      /** Bbox */
      bbox?:
        | [number, number, number, number]
        | [number, number, number, number, number, number]
        | null;
      /**
       * Type
       * @constant
       */
      type: 'MultiPolygon';
      /** Coordinates */
      coordinates: (
        | components['schemas']['Position2D']
        | components['schemas']['Position3D']
      )[][][];
    };
    /**
     * Polygon
     * @description Polygon Model
     */
    Polygon: {
      /** Bbox */
      bbox?:
        | [number, number, number, number]
        | [number, number, number, number, number, number]
        | null;
      /**
       * Type
       * @constant
       */
      type: 'Polygon';
      /** Coordinates */
      coordinates: (
        | components['schemas']['Position2D']
        | components['schemas']['Position3D']
      )[][];
    };
    /** FieldsParam[HutSchemaDetails] */
    FieldsParam_HutSchemaDetails_: {
      /**
       * Include
       * @description Comma separated list with field names, use `__all__` in order to include every field.
       */
      include?: unknown;
      /**
       * Exclude
       * @description Comma separated list with field names, if set it uses all fields except the excluded ones.
       */
      exclude?: unknown;
    };
    /** FieldsParam[OrganizationOptional] */
    FieldsParam_OrganizationOptional_: {
      /**
       * Include
       * @description Comma separated list with field names, use `__all__` in order to include every field.
       */
      include?: unknown;
      /**
       * Exclude
       * @description Comma separated list with field names, if set it uses all fields except the excluded ones.
       */
      exclude?: unknown;
    };
    /** OrganizationOptional */
    OrganizationOptional: {
      /** Name */
      name: string | null;
      /** Fullname */
      fullname?: string | null;
      /** Description */
      description?: string | null;
      /** Attribution */
      attribution?: string | null;
      /** Url */
      url?: string | null;
      /** Config */
      config?: {
        [key: string]: unknown;
      } | null;
      /** Props Schema */
      props_schema?: {
        [key: string]: unknown;
      } | null;
      /** Order */
      order?: number | null;
      /** Slug */
      slug?: string | null;
      /**
       * Link patten to object
       * @description Link pattern to corresponding object. Variables to use: {{id}}, {{lang}}, {{props}}, {{config}}.)
       */
      link_hut_pattern?: string | null;
      /**
       * Logo
       * @description Organiztion logo as image
       * @default organizations/logos/missing.png
       */
      logo?: string | null;
      /**
       * Aktiv
       * @default true
       */
      is_active?: boolean | null;
      /**
       * Public
       * @default false
       */
      is_public?: boolean | null;
      /**
       * Light Color
       * @description light theme color as hex number with #
       * @default #4B8E43
       */
      color_light?: string | null;
      /**
       * Dark Color
       * @description dark theme color as hex number with #
       * @default #61B958
       */
      color_dark?: string | null;
    };
    /** ResponseSchema */
    ResponseSchema: {
      /** Message */
      message: string;
      /** Id */
      id: number;
    };
    /** FeedbackCreate */
    FeedbackCreate: {
      /** Urls */
      urls?: string[] | null;
      /** Email */
      email: string;
      /** Subject */
      subject: string;
      /** Message */
      message: string;
      /** Get Updates */
      get_updates: boolean;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}

export type $defs = Record<string, never>;

export type external = Record<string, never>;

export interface operations {
  /**
   * Get hut bookings (deprecated)
   * @deprecated
   * @description **DEPRECATED**: Use `/huts/availability.geojson` instead. This endpoint will be removed in a future version.
   */
  get_hut_bookings: {
    parameters: {
      query?: {
        /** @description Select language code: de, en, fr, it. */
        lang?: string;
        /** @description Comma separated list with slugs to use, per default all. */
        slugs?: string | null;
        /** @description Show bookings for this many days. */
        days?: number;
        /** @description Date to start with bookings (yyyy-mm-dd, 'now' or 'weekend'). */
        date?: string | ('now' | 'weekend');
        /** @description Time in seconds to wait between requests to the booking service for each hut. If not set uses recommanded default value. */
        request_interval?: number | null;
      };
    };
    responses: {
      /** @description OK */
      200: {
        content: {
          'application/json': components['schemas']['HutBookingsSchema'][];
        };
      };
    };
  };
  /**
   * Get hut bookings as GeoJSON (deprecated)
   * @deprecated
   * @description **DEPRECATED**: Use `/huts/availability.geojson` instead. This endpoint will be removed in a future version.
   */
  get_hut_bookings_geojson: {
    parameters: {
      query?: {
        /** @description Select language code: de, en, fr, it. */
        lang?: string;
        /** @description Comma separated list with slugs to use, per default all. */
        slugs?: string | null;
        /** @description Show bookings for this many days. */
        days?: number;
        /** @description Date to start with bookings (yyyy-mm-dd, 'now' or 'weekend'). */
        date?: string | ('now' | 'weekend');
        /** @description Time in seconds to wait between requests to the booking service for each hut. If not set uses recommanded default value. */
        request_interval?: number | null;
      };
    };
    responses: {
      /** @description OK */
      200: {
        content: {
          'application/json': components['schemas']['HutBookingsFeatureCollection'];
        };
      };
    };
  };
  /** Get Hut Types */
  get_hut_types: {
    parameters: {
      query?: {
        /** @description Select language code: de, en, fr, it. */
        lang?: string;
        /** @description Comma separated list with field names, use `__all__` in order to include every field. */
        include?: unknown;
        /** @description Comma separated list with field names, if set it uses all fields except the excluded ones. */
        exclude?: unknown;
      };
    };
    responses: {
      /** @description OK */
      200: {
        content: {
          'application/json': components['schemas']['HutTypeDetailSchema'][];
        };
      };
    };
  };
  /** Get Hut Type Records */
  get_hut_type_records: {
    parameters: {
      query?: {
        /** @description Select language code: de, en, fr, it. */
        lang?: string;
        /** @description Comma separated list with field names, use `__all__` in order to include every field. */
        include?: unknown;
        /** @description Comma separated list with field names, if set it uses all fields except the excluded ones. */
        exclude?: unknown;
      };
    };
    responses: {
      /** @description OK */
      200: {
        content: {
          'application/json': {
            [key: string]: components['schemas']['HutTypeDetailSchema'];
          };
        };
      };
    };
  };
  /**
   * Get Hut Availability Geojson
   * @description Get availability data as GeoJSON FeatureCollection for map visualization.
   */
  get_hut_availability_geojson: {
    parameters: {
      query?: {
        /** @description Select language code: de, en, fr, it. */
        lang?: string;
        /** @description Comma-separated list of hut slugs to filter (e.g., 'aarbiwak,almageller'). If not set, returns all huts. */
        slugs?: string | null;
        /** @description Number of days to fetch from start date. */
        days?: number;
        /** @description Pagination offset for results. */
        offset?: number;
        /** @description Maximum number of huts to return. If not set, returns all matching huts. */
        limit?: number | null;
      };
      path: {
        /** @description Start date. Accepts ISO dates (2026-01-15, 26-01-15), European format (15.01.2026), or keywords: 'now', 'today', 'weekend'. */
        date: string;
      };
    };
    responses: {
      /** @description OK */
      200: {
        content: {
          'application/json': components['schemas']['HutAvailabilityFeatureCollection'];
        };
      };
    };
  };
  /**
   * Get Hut Availability Current
   * @description Get current availability data for a specific hut with detailed metadata and booking links.
   */
  get_hut_availability_current: {
    parameters: {
      query?: {
        /** @description Select language code: de, en, fr, it. */
        lang?: string;
        /** @description Number of days to fetch from start date. */
        days?: number;
      };
      path: {
        slug: string;
        /** @description Start date. Accepts ISO dates (2026-01-15, 26-01-15), European format (15.01.2026), or keywords: 'now', 'today', 'weekend'. */
        date: string;
      };
    };
    responses: {
      /** @description OK */
      200: {
        content: {
          'application/json': components['schemas']['CurrentAvailabilitySchema'];
        };
      };
    };
  };
  /**
   * Get Hut Availability Trend
   * @description Get historical availability trend data showing how availability changed over time for a specific date.
   */
  get_hut_availability_trend: {
    parameters: {
      query?: {
        /** @description Select language code: de, en, fr, it. */
        lang?: string;
        /** @description How many days back to show history from the target date. */
        limit?: number;
      };
      path: {
        slug: string;
        /** @description Target date to analyze. Accepts ISO dates (2026-01-15, 26-01-15), European format (15.01.2026), or keywords: 'now', 'today', 'weekend'. */
        date: string;
      };
    };
    responses: {
      /** @description OK */
      200: {
        content: {
          'application/json': components['schemas']['AvailabilityTrendSchema'];
        };
      };
    };
  };
  /**
   * Get Huts
   * @description Get a list with huts.
   */
  get_huts: {
    parameters: {
      query?: {
        /** @description Select language code: de, en, fr, it. */
        lang?: string;
        offset?: number;
        limit?: number | null;
        is_modified?: 'true' | 'false' | 'unset';
        is_public?: 'true' | 'false' | 'unset';
        is_active?: 'true' | 'false' | 'unset';
      };
    };
    responses: {
      /** @description OK */
      200: {
        content: {
          'application/json': components['schemas']['HutSchemaDetails'][];
        };
      };
    };
  };
  /** Get Huts Geojson */
  get_huts_geojson: {
    parameters: {
      query?: {
        /** @description Select language code: de, en, fr, it. */
        lang?: string;
        offset?: number;
        limit?: number | null;
        embed_all?: boolean;
        embed_type?: boolean;
        embed_owner?: boolean;
        embed_capacity?: boolean;
        embed_sources?: boolean;
        include_elevation?: boolean;
        include_name?: boolean;
        flat?: boolean;
      };
    };
    responses: {
      /** @description OK */
      200: {
        content: {
          'application/json': components['schemas']['FeatureCollection'];
        };
      };
    };
  };
  /**
   * Get Hut
   * @description Get a hut by its slug.
   */
  get_hut: {
    parameters: {
      query?: {
        /** @description Select language code: de, en, fr, it. */
        lang?: string;
        /** @description Comma separated list with field names, use `__all__` in order to include every field. */
        include?: unknown;
        /** @description Comma separated list with field names, if set it uses all fields except the excluded ones. */
        exclude?: unknown;
      };
      path: {
        slug: string;
      };
    };
    responses: {
      /** @description OK */
      200: {
        content: {
          'application/json': components['schemas']['HutSchemaDetails'];
        };
      };
    };
  };
  /**
   * Get Organizations
   * @description Get a list of all organizations used for the huts.
   */
  get_organizations: {
    parameters: {
      query?: {
        /** @description Select language code: de, en, fr, it. */
        lang?: string;
        /** @description Comma separated list with field names, use `__all__` in order to include every field. */
        include?: unknown;
        /** @description Comma separated list with field names, if set it uses all fields except the excluded ones. */
        exclude?: unknown;
        is_public?: boolean | null;
      };
    };
    responses: {
      /** @description OK */
      200: {
        content: {
          'application/json': components['schemas']['OrganizationOptional'][];
        };
      };
    };
  };
  /** Get Organization */
  get_organization: {
    parameters: {
      query?: {
        /** @description Select language code: de, en, fr, it. */
        lang?: string;
        /** @description Comma separated list with field names, use `__all__` in order to include every field. */
        include?: unknown;
        /** @description Comma separated list with field names, if set it uses all fields except the excluded ones. */
        exclude?: unknown;
      };
      path: {
        slug: string;
      };
    };
    responses: {
      /** @description OK */
      200: {
        content: {
          'application/json': components['schemas']['OrganizationOptional'];
        };
      };
    };
  };
  /** Create Feedback */
  server_apps_feedbacks_api_create_feedback: {
    parameters: {
      query?: {
        send_email?: boolean;
      };
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['FeedbackCreate'];
      };
    };
    responses: {
      /** @description OK */
      200: {
        content: {
          'application/json': components['schemas']['ResponseSchema'];
        };
      };
    };
  };
}
