/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  '/v1/huts/bookings': {
    /** Get Hut Bookings */
    get: operations['get_hut_bookings'];
  };
  '/v1/huts/bookings.geojson': {
    /** Get Hut Bookings Geojson */
    get: operations['get_hut_bookings_geojson'];
  };
  '/v1/huts/huts': {
    /**
     * Get Huts
     * @description Get a list with huts.
     */
    get: operations['get_huts'];
  };
  '/v1/huts/huts.geojson': {
    /** Get Huts Geojson */
    get: operations['get_huts_geojson'];
  };
  '/v1/huts/{slug}': {
    /**
     * Get Hut
     * @description Get a hut by its slug.
     */
    get: operations['get_hut'];
  };
  '/v1/huts/types/list': {
    /** Get Hut Types */
    get: operations['get_hut_types'];
  };
  '/v1/huts/types/records': {
    /** Get Hut Type Records */
    get: operations['get_hut_type_records'];
  };
  '/v1/organizations/': {
    /**
     * Get Organizations
     * @description Get a list of all organizations used for the huts.
     */
    get: operations['get_organizations'];
  };
  '/v1/organizations/{slug}': {
    /** Get Organization */
    get: operations['get_organization'];
  };
}

export type webhooks = Record<string, never>;

export interface components {
  schemas: {
    /** HutBookingsQuery */
    HutBookingsQuery: {
      /**
       * Slugs
       * @description Comma separated list with slugs to use, per default all.
       */
      slugs?: string | null;
      /**
       * Days
       * @description Show bookings for this many days.
       * @default 1
       */
      days?: number;
      /**
       * Date
       * @description Date to start with booking (yyyy-mm-dd or now).
       * @default now
       */
      date?: string | 'now';
    };
    /** HutBookingSchema */
    HutBookingSchema: {
      /** Link */
      link: string;
      /**
       * Date
       * Format: date
       */
      date: string;
      reservation_status: components['schemas']['ReservationStatusEnum'];
      /** Free */
      free: number;
      /** Total */
      total: number;
      /** Occupancy Percent */
      occupancy_percent: number;
      /** Occupancy Steps */
      occupancy_steps: number;
      occupancy_status: components['schemas']['OccupancyStatusEnum'];
      /**
       * Hut Type
       * @default unknown
       */
      hut_type?: string;
    };
    /** HutBookingsSchema */
    HutBookingsSchema: {
      /** Slug */
      slug: string;
      /** Hut Id */
      hut_id: number;
      /**
       * Source
       * @description Source slug, e.g. hrs
       */
      source: string;
      /** Days */
      days: number;
      /** Link */
      link: string;
      /**
       * Start Date
       * Format: date
       */
      start_date: string;
      /** Bookings */
      bookings: components['schemas']['HutBookingSchema'][];
      location: components['schemas']['LocationSchema'];
    };
    /**
     * LocationSchema
     * @description Location with longitude, latitude and optional elevation in WSG84.
     *
     * Attributes:
     *     lon: Longitude (x).
     *     lat: Latitude (y).
     *     ele: Elevation in meter.
     */
    LocationSchema: {
      /** Latitude (y) in WGS84 */
      lat: number;
      /** Longitude (x) in WGS84 */
      lon: number;
    };
    /**
     * OccupancyStatusEnum
     * @description Enum with with occuptation status.
     * @enum {string}
     */
    OccupancyStatusEnum:
      | 'unknown'
      | 'empty'
      | 'low'
      | 'medium'
      | 'high'
      | 'full';
    /**
     * ReservationStatusEnum
     * @description Enum with reservation status.
     * @enum {string}
     */
    ReservationStatusEnum:
      | 'unknown'
      | 'possible'
      | 'not_possible'
      | 'not_online';
    /** Feature[Point, HutBookingsProps] */
    Feature_Point_HutBookingsProps_: {
      /** Bbox */
      bbox?:
        | [number, number, number, number]
        | [number, number, number, number, number, number]
        | null;
      /**
       * Type
       * @constant
       * @enum {string}
       */
      type: 'Feature';
      geometry: components['schemas']['Point'] | null;
      properties: components['schemas']['HutBookingsProps'] | null;
      /** Id */
      id?: number | string | null;
    };
    /** HutBookingsFeatureCollection */
    HutBookingsFeatureCollection: {
      /** Bbox */
      bbox?:
        | [number, number, number, number]
        | [number, number, number, number, number, number]
        | null;
      /**
       * Type
       * @constant
       * @enum {string}
       */
      type: 'FeatureCollection';
      /** Features */
      features: components['schemas']['Feature_Point_HutBookingsProps_'][];
    };
    /** HutBookingsProps */
    HutBookingsProps: {
      /** Slug */
      slug: string;
      /** Hut Id */
      hut_id: number;
      /**
       * Source
       * @description Source slug, e.g. hrs
       */
      source: string;
      /** Days */
      days: number;
      /** Link */
      link: string;
      /**
       * Start Date
       * Format: date
       */
      start_date: string;
      /** Bookings */
      bookings: components['schemas']['HutBookingSchema'][];
    };
    /**
     * Point
     * @description Point Model
     */
    Point: {
      /** Bbox */
      bbox?:
        | [number, number, number, number]
        | [number, number, number, number, number, number]
        | null;
      /**
       * Type
       * @constant
       * @enum {string}
       */
      type: 'Point';
      /** Coordinates */
      coordinates: [number, number] | [number, number, number];
    };
    /**
     * TristateEnum
     * @description Tristate enum with `true`, `false` and `unset`.
     * @enum {string}
     */
    TristateEnum: 'true' | 'false' | 'unset';
    /**
     * AnswerEnum
     * @description Enum with open values.
     * @enum {string}
     */
    AnswerEnum: 'yes' | 'maybe' | 'no' | 'unknown';
    CountryTuple: [string, string];
    /** HutSchemaDetails */
    HutSchemaDetails: {
      /** Slug */
      slug: string;
      /** Name */
      name: string | null;
      /** Description */
      description: string | null;
      /** Description Attribution */
      description_attribution: string;
      owner: components['schemas']['OwnerSchema'] | null;
      /** Review Status */
      review_status?: string | null;
      /** Is Public */
      is_public?: boolean | null;
      /** Is Active */
      is_active?: boolean | null;
      /** Is Modified */
      is_modified?: boolean | null;
      type_open?: components['schemas']['HutTypeSchema'] | null;
      type_closed?: components['schemas']['HutTypeSchema'] | null;
      /** Elevation */
      elevation?: number | null;
      location?: components['schemas']['LocationSchema'] | null;
      /** Url */
      url?: string | null;
      country?: components['schemas']['CountryTuple'] | null;
      /** Capacity Open */
      capacity_open?: number | null;
      /** Capacity Closed */
      capacity_closed?: number | null;
      /** Sources */
      sources: components['schemas']['OrganizationDetailSchema'][] | null;
      /**
       * Photos
       * @default
       */
      photos?: string;
      /**
       * Photos Attribution
       * @default
       */
      photos_attribution?: string;
      open_monthly?: components['schemas']['OpenMonthlySchema'] | null;
      /** Edit Link */
      edit_link?: string | null;
      /** Translations */
      translations?: unknown;
    };
    /** HutTypeSchema */
    HutTypeSchema: {
      /** Level */
      level?: number | null;
      /** Slug */
      slug: string;
      /** Name */
      name: string | null;
      /** Symbol */
      symbol: string | null;
      /** Symbol Simple */
      symbol_simple: string | null;
      /** Icon */
      icon: string | null;
    };
    /**
     * OpenMonthlySchema
     * @description Shows for every month if it is usally, open, partially open or closed.
     * Can be accessed as index, but it starts with 1 (month_01)!.
     *
     * Attributes:
     *     url: URL which shows if it is open or not.
     *     month_mm (OpenMonthly): Month (starting with 01).
     */
    OpenMonthlySchema: {
      /**
       * Url
       * @description URL which shows if it is open or not.
       * @default
       */
      url?: string;
      /** @default unknown */
      month_01?: components['schemas']['AnswerEnum'];
      /** @default unknown */
      month_02?: components['schemas']['AnswerEnum'];
      /** @default unknown */
      month_03?: components['schemas']['AnswerEnum'];
      /** @default unknown */
      month_04?: components['schemas']['AnswerEnum'];
      /** @default unknown */
      month_05?: components['schemas']['AnswerEnum'];
      /** @default unknown */
      month_06?: components['schemas']['AnswerEnum'];
      /** @default unknown */
      month_07?: components['schemas']['AnswerEnum'];
      /** @default unknown */
      month_08?: components['schemas']['AnswerEnum'];
      /** @default unknown */
      month_09?: components['schemas']['AnswerEnum'];
      /** @default unknown */
      month_10?: components['schemas']['AnswerEnum'];
      /** @default unknown */
      month_11?: components['schemas']['AnswerEnum'];
      /** @default unknown */
      month_12?: components['schemas']['AnswerEnum'];
      [key: string]: unknown;
    };
    /** OrganizationDetailSchema */
    OrganizationDetailSchema: {
      /** Slug */
      slug: string;
      /** Name */
      name: string;
      /** Fullname */
      fullname: string;
      /** Link */
      link: string;
      /** Logo */
      logo: string;
    };
    /** OwnerSchema */
    OwnerSchema: {
      /** Name */
      name: string | null;
      /** Slug */
      slug: string;
      /**
       * Adresse (URL)
       * @default
       */
      url?: string;
    };
    /** BaseModel */
    BaseModel: Record<string, never>;
    /**
     * Feature
     * @description Feature Model
     */
    Feature: {
      /** Bbox */
      bbox?:
        | [number, number, number, number]
        | [number, number, number, number, number, number]
        | null;
      /**
       * Type
       * @constant
       * @enum {string}
       */
      type: 'Feature';
      /** Geometry */
      geometry:
        | (
            | components['schemas']['Point']
            | components['schemas']['MultiPoint']
            | components['schemas']['LineString']
            | components['schemas']['MultiLineString']
            | components['schemas']['Polygon']
            | components['schemas']['MultiPolygon']
            | components['schemas']['GeometryCollection']
          )
        | null;
      /** Properties */
      properties:
        | Record<string, never>
        | components['schemas']['BaseModel']
        | null;
      /** Id */
      id?: number | string | null;
    };
    /**
     * FeatureCollection
     * @description FeatureCollection Model
     */
    FeatureCollection: {
      /** Bbox */
      bbox?:
        | [number, number, number, number]
        | [number, number, number, number, number, number]
        | null;
      /**
       * Type
       * @constant
       * @enum {string}
       */
      type: 'FeatureCollection';
      /** Features */
      features: components['schemas']['Feature'][];
    };
    /**
     * GeometryCollection
     * @description GeometryCollection Model
     */
    GeometryCollection: {
      /** Bbox */
      bbox?:
        | [number, number, number, number]
        | [number, number, number, number, number, number]
        | null;
      /**
       * Type
       * @constant
       * @enum {string}
       */
      type: 'GeometryCollection';
      /** Geometries */
      geometries: (
        | components['schemas']['Point']
        | components['schemas']['MultiPoint']
        | components['schemas']['LineString']
        | components['schemas']['MultiLineString']
        | components['schemas']['Polygon']
        | components['schemas']['MultiPolygon']
        | components['schemas']['GeometryCollection']
      )[];
    };
    /**
     * LineString
     * @description LineString Model
     */
    LineString: {
      /** Bbox */
      bbox?:
        | [number, number, number, number]
        | [number, number, number, number, number, number]
        | null;
      /**
       * Type
       * @constant
       * @enum {string}
       */
      type: 'LineString';
      /** Coordinates */
      coordinates: ([number, number] | [number, number, number])[];
    };
    /**
     * MultiLineString
     * @description MultiLineString Model
     */
    MultiLineString: {
      /** Bbox */
      bbox?:
        | [number, number, number, number]
        | [number, number, number, number, number, number]
        | null;
      /**
       * Type
       * @constant
       * @enum {string}
       */
      type: 'MultiLineString';
      /** Coordinates */
      coordinates: ([number, number] | [number, number, number])[][];
    };
    /**
     * MultiPoint
     * @description MultiPoint Model
     */
    MultiPoint: {
      /** Bbox */
      bbox?:
        | [number, number, number, number]
        | [number, number, number, number, number, number]
        | null;
      /**
       * Type
       * @constant
       * @enum {string}
       */
      type: 'MultiPoint';
      /** Coordinates */
      coordinates: ([number, number] | [number, number, number])[];
    };
    /**
     * MultiPolygon
     * @description MultiPolygon Model
     */
    MultiPolygon: {
      /** Bbox */
      bbox?:
        | [number, number, number, number]
        | [number, number, number, number, number, number]
        | null;
      /**
       * Type
       * @constant
       * @enum {string}
       */
      type: 'MultiPolygon';
      /** Coordinates */
      coordinates: ([number, number] | [number, number, number])[][][];
    };
    /**
     * Polygon
     * @description Polygon Model
     */
    Polygon: {
      /** Bbox */
      bbox?:
        | [number, number, number, number]
        | [number, number, number, number, number, number]
        | null;
      /**
       * Type
       * @constant
       * @enum {string}
       */
      type: 'Polygon';
      /** Coordinates */
      coordinates: ([number, number] | [number, number, number])[][];
    };
    /** FieldsParam[HutSchemaDetails] */
    FieldsParam_HutSchemaDetails_: {
      /**
       * Include
       * @description Comma separated list with field names, use `__all__` in order to include every field.
       */
      include?: unknown;
      /**
       * Exclude
       * @description Comma separated list with field names, if set it uses all fields except the excluded ones.
       */
      exclude?: unknown;
    };
    /** FieldsParam[HutTypeDetailSchema] */
    FieldsParam_HutTypeDetailSchema_: {
      /**
       * Include
       * @description Comma separated list with field names, use `__all__` in order to include every field.
       */
      include?: unknown;
      /**
       * Exclude
       * @description Comma separated list with field names, if set it uses all fields except the excluded ones.
       */
      exclude?: unknown;
    };
    /** HutTypeDetailSchema */
    HutTypeDetailSchema: {
      /** Slug */
      slug: string;
      /** Name */
      name: string;
      /**
       * Description
       * @default
       */
      description?: string;
      /**
       * Symbol
       * @description Normal icon
       */
      symbol?: string | null;
      /**
       * Level
       * @description Comfort level, higher is more comfort
       */
      level?: number | null;
      /**
       * Symbol Simple
       * @description Simple icon
       */
      symbol_simple?: string | null;
      /**
       * Icon
       * @description Black icon
       */
      icon?: string | null;
    };
    /** FieldsParam[OrganizationOptional] */
    FieldsParam_OrganizationOptional_: {
      /**
       * Include
       * @description Comma separated list with field names, use `__all__` in order to include every field.
       */
      include?: unknown;
      /**
       * Exclude
       * @description Comma separated list with field names, if set it uses all fields except the excluded ones.
       */
      exclude?: unknown;
    };
    /** OrganizationOptional */
    OrganizationOptional: {
      /** Name */
      name: string | null;
      /** Fullname */
      fullname?: string | null;
      /** Description */
      description?: string | null;
      /** Attribution */
      attribution?: string | null;
      /** Url */
      url?: string | null;
      /** Config */
      config?: Record<string, never> | null;
      /** Props Schema */
      props_schema?: Record<string, never> | null;
      /** Order */
      order?: number | null;
      /** Slug */
      slug?: string | null;
      /**
       * Link patten to object
       * @description Link pattern to corresponding object. Variables to use: {{id}}, {{lang}}, {{props}}, {{config}}.)
       */
      link_hut_pattern?: string | null;
      /**
       * Logo
       * @description Organiztion logo as image
       */
      logo?: string | null;
      /** Aktiv */
      is_active?: boolean | null;
      /** Public */
      is_public?: boolean | null;
      /**
       * Light Color
       * @description light theme color as hex number with #
       */
      color_light?: string | null;
      /**
       * Dark Color
       * @description dark theme color as hex number with #
       */
      color_dark?: string | null;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}

export type $defs = Record<string, never>;

export type external = Record<string, never>;

export interface operations {
  /** Get Hut Bookings */
  get_hut_bookings: {
    parameters: {
      query?: {
        /** @description Select language code: de, en, fr, it. */
        lang?: string;
        /** @description Comma separated list with slugs to use, per default all. */
        slugs?: string | null;
        /** @description Show bookings for this many days. */
        days?: number;
        /** @description Date to start with booking (yyyy-mm-dd or now). */
        date?: string | 'now';
      };
    };
    responses: {
      /** @description OK */
      200: {
        content: {
          'application/json': components['schemas']['HutBookingsSchema'][];
        };
      };
    };
  };
  /** Get Hut Bookings Geojson */
  get_hut_bookings_geojson: {
    parameters: {
      query?: {
        /** @description Select language code: de, en, fr, it. */
        lang?: string;
        /** @description Comma separated list with slugs to use, per default all. */
        slugs?: string | null;
        /** @description Show bookings for this many days. */
        days?: number;
        /** @description Date to start with booking (yyyy-mm-dd or now). */
        date?: string | 'now';
      };
    };
    responses: {
      /** @description OK */
      200: {
        content: {
          'application/json': components['schemas']['HutBookingsFeatureCollection'];
        };
      };
    };
  };
  /**
   * Get Huts
   * @description Get a list with huts.
   */
  get_huts: {
    parameters: {
      query?: {
        /** @description Select language code: de, en, fr, it. */
        lang?: string;
        offset?: number;
        limit?: number | null;
        is_modified?: 'true' | 'false' | 'unset';
        is_public?: 'true' | 'false' | 'unset';
        is_active?: 'true' | 'false' | 'unset';
      };
    };
    responses: {
      /** @description OK */
      200: {
        content: {
          'application/json': components['schemas']['HutSchemaDetails'][];
        };
      };
    };
  };
  /** Get Huts Geojson */
  get_huts_geojson: {
    parameters: {
      query?: {
        /** @description Select language code: de, en, fr, it. */
        lang?: string;
        offset?: number;
        limit?: number | null;
        embed_all?: boolean;
        embed_type?: boolean;
        embed_owner?: boolean;
        embed_capacity?: boolean;
        embed_sources?: boolean;
        include_elevation?: boolean;
        include_name?: boolean;
        flat?: boolean;
      };
    };
    responses: {
      /** @description OK */
      200: {
        content: {
          'application/json': components['schemas']['FeatureCollection'];
        };
      };
    };
  };
  /**
   * Get Hut
   * @description Get a hut by its slug.
   */
  get_hut: {
    parameters: {
      query?: {
        /** @description Select language code: de, en, fr, it. */
        lang?: string;
        /** @description Comma separated list with field names, use `__all__` in order to include every field. */
        include?: unknown;
        /** @description Comma separated list with field names, if set it uses all fields except the excluded ones. */
        exclude?: unknown;
      };
      path: {
        slug: string;
      };
    };
    responses: {
      /** @description OK */
      200: {
        content: {
          'application/json': components['schemas']['HutSchemaDetails'];
        };
      };
    };
  };
  /** Get Hut Types */
  get_hut_types: {
    parameters: {
      query?: {
        /** @description Select language code: de, en, fr, it. */
        lang?: string;
        /** @description Comma separated list with field names, use `__all__` in order to include every field. */
        include?: unknown;
        /** @description Comma separated list with field names, if set it uses all fields except the excluded ones. */
        exclude?: unknown;
      };
    };
    responses: {
      /** @description OK */
      200: {
        content: {
          'application/json': components['schemas']['HutTypeDetailSchema'][];
        };
      };
    };
  };
  /** Get Hut Type Records */
  get_hut_type_records: {
    parameters: {
      query?: {
        /** @description Select language code: de, en, fr, it. */
        lang?: string;
        /** @description Comma separated list with field names, use `__all__` in order to include every field. */
        include?: unknown;
        /** @description Comma separated list with field names, if set it uses all fields except the excluded ones. */
        exclude?: unknown;
      };
    };
    responses: {
      /** @description OK */
      200: {
        content: {
          'application/json': {
            [key: string]: components['schemas']['HutTypeDetailSchema'];
          };
        };
      };
    };
  };
  /**
   * Get Organizations
   * @description Get a list of all organizations used for the huts.
   */
  get_organizations: {
    parameters: {
      query?: {
        /** @description Select language code: de, en, fr, it. */
        lang?: string;
        /** @description Comma separated list with field names, use `__all__` in order to include every field. */
        include?: unknown;
        /** @description Comma separated list with field names, if set it uses all fields except the excluded ones. */
        exclude?: unknown;
        is_public?: boolean | null;
      };
    };
    responses: {
      /** @description OK */
      200: {
        content: {
          'application/json': components['schemas']['OrganizationOptional'][];
        };
      };
    };
  };
  /** Get Organization */
  get_organization: {
    parameters: {
      query?: {
        /** @description Select language code: de, en, fr, it. */
        lang?: string;
        /** @description Comma separated list with field names, use `__all__` in order to include every field. */
        include?: unknown;
        /** @description Comma separated list with field names, if set it uses all fields except the excluded ones. */
        exclude?: unknown;
      };
      path: {
        slug: string;
      };
    };
    responses: {
      /** @description OK */
      200: {
        content: {
          'application/json': components['schemas']['OrganizationOptional'];
        };
      };
    };
  };
}
