#!/usr/bin/env node
//
// Generate the typed API client AND the pinned API version from the
// backend's OpenAPI schema — both from the SAME schema, so the types and
// the pin can never drift apart.
//
//   node scripts/gen-api.mjs [--local] [--base https://…] [--version 2026-10-01]
//
// - default: uses the latest schema (https://api.wodore.com); the pin is
//   set to its info.version (= current API version — the literal
//   "unreleased" while a breaking change is unfrozen) — routine additive
//   backend changes are a no-op for the pin; after a NEW API version was
//   released this ABSORBS it (types + pin bump together, visible in the
//   diff — review exactly like any contract change).
// - --version <date>: generates from that version's frozen snapshot
//   (/v1/openapi.json?api_version=…) — use when the app must stay on an
//   older contract while a newer version exists.
// - --local: schema from http://127.0.0.1:8000 instead of production.
//
// Outputs (both prettier-formatted, both committed):
// - src/clients/wodore_v1.d.ts  (openapi-typescript)
// - src/clients/apiVersion.ts   (PINNED_API_VERSION, generated — do not edit)
//
/* global fetch */
//
import { execFileSync } from 'node:child_process';
import { mkdtempSync, rmSync, writeFileSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';

const PROD_BASE = 'https://api.wodore.com';
const LOCAL_BASE = 'http://127.0.0.1:8000';

const args = process.argv.slice(2);
const local = args.includes('--local');
const baseIdx = args.indexOf('--base');
const versionIdx = args.indexOf('--version');
const version = versionIdx !== -1 ? args[versionIdx + 1] : undefined;

if (version && !/^\d{4}-\d{2}-\d{2}$/.test(version)) {
  console.error(`[gen-api] --version must be a date (YYYY-MM-DD), got: ${version}`);
  process.exit(1);
}

const base = baseIdx !== -1 ? args[baseIdx + 1] : local ? LOCAL_BASE : PROD_BASE;
const url = `${base}/v1/openapi.json${version ? `?api_version=${version}` : ''}`;
console.log(`[gen-api] fetching schema: ${url}`);

const response = await fetch(url);
if (!response.ok) {
  console.error(`[gen-api] schema fetch failed: HTTP ${response.status}`);
  process.exit(1);
}
const schema = await response.json();

// The backend serves the registry's CURRENT version as info.version — a
// date for released versions, the literal "unreleased" between api-freeze
// and release (server/apps/apiversions/registry.py). Both are valid pins.
const schemaVersion = schema?.info?.version;
if (
  !/^\d{4}-\d{2}-\d{2}$/.test(String(schemaVersion ?? '')) &&
  schemaVersion !== 'unreleased'
) {
  console.error(
    `[gen-api] schema has no usable info.version (got: ${schemaVersion}) — ` +
      'expected a date (YYYY-MM-DD) or "unreleased".',
  );
  process.exit(1);
}
if (version && schemaVersion !== version) {
  console.error(
    `[gen-api] requested version ${version} but schema serves ${schemaVersion} ` +
      '(proxy cache or wrong backend?) — refusing to generate mismatched types.',
  );
  process.exit(1);
}

// Generate from the fetched schema (not the URL) so types and pin provably
// come from the same document.
const tmp = mkdtempSync(join(tmpdir(), 'wd-genapi-'));
try {
  const schemaFile = join(tmp, 'openapi.json');
  writeFileSync(schemaFile, JSON.stringify(schema));

  execFileSync(
    'npx',
    ['openapi-typescript', schemaFile, '-o', './src/clients/wodore_v1.d.ts'],
    { stdio: 'inherit' },
  );

  writeFileSync(
    './src/clients/apiVersion.ts',
    [
      '// GENERATED by scripts/gen-api.mjs (yarn gen:api / gen:api-local) — do not edit.',
      `// Source schema: ${url}`,
      `export const PINNED_API_VERSION = '${schemaVersion}';`,
      '',
    ].join('\n'),
  );

  execFileSync(
    'npx',
    [
      'prettier',
      '--write',
      './src/clients/wodore_v1.d.ts',
      './src/clients/apiVersion.ts',
    ],
    { stdio: 'inherit' },
  );

  console.log(`[gen-api] done — client + pin set to API version ${schemaVersion}`);
} finally {
  rmSync(tmp, { recursive: true, force: true });
}
